ServerEvents.recipes(sog => {

    sog.recipes.gtceu.mixer('reactive_blend')
    .itemInputs('2x draconicevolution:chaos_shard')
    .inputFluids(Fluid.of('gtceu:antimatter', 576))
    .circuit(19)
    .itemOutputs('8x kubejs:reactive_blend')
    .duration(20*50)
    .EUt((GTValues.VA[GTValues.UXV]))
    sog.recipes.gtceu.electric_blast_furnace('reactive_chaos_dust')
    .itemInputs('2x gtceu:cosmic_neutronium_dust', '4x kubejs:reactive_blend')
    .inputFluids('gtceu:aqua_regia 1000')
    .itemOutputs('8x kubejs:reactive_chaos_dust')
    .blastFurnaceTemp(15200)
    .duration(20*10)
    .EUt(GTValues.VA[GTValues.UXV]);
    sog.recipes.gtceu.mixer('reactive_chaos_pellet')
    .itemInputs('4x kubejs:reactive_chaos_dust')
    .inputFluids(Fluid.of('gtceu:awakened_draconium', 576))
    .circuit(19)
    .itemOutputs('2x kubejs:reactive_chaos_pellet')
    .duration(20*5)
    .EUt((GTValues.VA[GTValues.UXV]))
    sog.recipes.gtceu.mixer('infused_reactive_chaos_pellet')
    .itemInputs('4x kubejs:reactive_chaos_dust')
    .inputFluids(Fluid.of('gtceu:eternity', 10))
    .circuit(19)
    .itemOutputs('2x kubejs:infused_reactive_chaos_pellet')
    .duration(20*5)
    .EUt((GTValues.VA[GTValues.UXV]))
    sog.recipes.gtceu.arc_furnace('reactive_waste')
    .itemInputs('2x kubejs:reactive_chaos_waste')
    .inputFluids(Fluid.of('gtceu:antimatter', 576))
    .itemOutputs('1x kubejs:reactive_chaos_pellet')
    .duration(20*5)
    .EUt((GTValues.VA[GTValues.UXV]))
    sog.recipes.gtceu.csr('chaotic_pellet')
    .chancedInput('kubejs:reactive_chaos_pellet', 1000, 0)
    .chancedOutput('kubejs:reactive_chaos_waste', 500, 0)
    .duration(20*20)
    .EUt(-(GTValues.V[GTValues.MAX]))
    sog.recipes.gtceu.csr('infused_chaotic_pellet')
    .itemInputs('kubejs:infused_reactive_chaos_pellet')
    .duration(20*800)
    .EUt(-549755813888)

})