ServerEvents.recipes(event => {

    event.recipes.gtceu.dimensional_miner('asteroid_mining_1')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('7500x gtceu:moon_cosmic_iridium_ore')
    .itemOutputs('7500x gtceu:moon_cosmic_osmium_ore')
    .itemOutputs('7500x gtceu:moon_cosmic_tugsten_ore')
    .itemOutputs('7500x gtceu:moon_cosmic_titanium_ore')
    .itemOutputs('7500x gtceu:moon_cosmic_neutronium_ore')
    .circuit(1)
    .duration(20*20)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_2')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('75000x gtceu:moon_kaemite_ore')
    .itemOutputs('75000x gtceu:moon_resonant_naquadah_ore')
    .itemOutputs('75000x gtceu:moon_resonant_essence_ore')
    .circuit(2)
    .dimension('sogcore:asteroid_belt')
    .duration(20*20)
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_3')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('75000x gtceu:moon_chaos_ore')
    .itemOutputs('50000x gtceu:moon_draconium_ore')
    .itemOutputs('7500x gtceu:moon_awakened_draconium_ore')
    .itemOutputs('500x gtceu:moon_infinity_catalyst_ore')
    .circuit(3)
    .duration(20*10)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
    
    event.recipes.gtceu.dimensional_miner('asteroid_mining_3_2')
    .notConsumable('kubejs:dimensional_pump_module')
    .inputFluids([Fluid.of('gtceu:eternity', 5)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemOutputs('75000x gtceu:moon_chaos_ore')
    .itemOutputs('50000x gtceu:moon_draconium_ore')
    .itemOutputs('7500x gtceu:moon_awakened_draconium_ore')
    .itemOutputs('500x gtceu:moon_infinity_catalyst_ore')
    .chancedFluidOutput('gtceu:stellar_matter_plasma 5000', 2500, 0)
    .chancedFluidOutput('gtceu:universium 2000', 1500, 0)
    .chancedFluidOutput('gtceu:molten_space_time 100', 1500, 0)
    .circuit(3)
    .duration(20*20)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);

    event.recipes.gtceu.dimensional_miner('asteroid_mining_4')
    .inputFluids([Fluid.of('gtceu:eternity', 500)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('1000000x gtceu:moon_draconium_ore')
    .circuit(4)
    .duration(20*40)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
    event.recipes.gtceu.dimensional_miner('asteroid_mining_5')
    .inputFluids([Fluid.of('gtceu:eternity', 500)])
    .inputFluids([Fluid.of('gtceu:drilling_fluid', 16000)])
    .itemInputs('gtceu:neutronium_drill_head')
    .itemOutputs('1000000x gtceu:moon_chaos_ore')
    .circuit(5)
    .duration(20*40)
    .dimension('sogcore:asteroid_belt')
    .EUt(GTValues.VA[GTValues.UIV]);
})
