GTCEuStartupEvents.registry('gtceu:material', event => {

    event.create('isocitric_acid')
    .fluid()
    .color(0xd3d3d3)
    event.create('oxalic_acid')
    .fluid()
    .color(0xffffff)
    event.create('pentadecanoic_acid')
    .fluid()
    .color(0xd3d3d3)
    event.create('ferulic_acid')
    .fluid()
    .color(0xffffff)
    event.create('glutamic_acid')
    .fluid()
    .color(0xffffff)
})