GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('stasis_phase_shifter')
        .category('multiblocks')
        .setEUIO('in')
        .setMaxIOSize(4, 4, 4, 4)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.REPLICATOR)
})





GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('stasis_phase_shifter', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('stasis_phase_shifter')
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(() => Block.getBlock('gtceu:frostproof_machine_casing'))
        .pattern(definition => FactoryBlockPattern.start()      
        .aisle('CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC', '###################', '###################', '###################', '###################', '###################', 'CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC', '###################', '###################', '###################', '###################', '###################', 'CDDDDDC#####CDDDDDC', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D##C##D', 'CDDDDDC#####CDDCDDC', '###############C###', '###############C###', '###############C###', '###############C###', '###############C###', 'CDDDDDC#####CDDCDDC', 'D#####D#####D##C##D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CAC#D#####D#CAC#D', 'D#AFA#########AFA#D', 'D#CAC#D#####D#CAC#D', 'D#C#C#D#####D#####D', 'CDC#CDC#####CDD#DDC', '##C#C##############', '##C#C##############', '##C#C##############', '##C#C##############', '##C#C##############', 'CDC#CDC#####CDD#DDC', 'D#C#C#D#####D#####D', 'D#CAC#D#####D#CAC#D', 'D#AFA#########AFA#D', 'D#CAC#D#####D#CAC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D##C##D', 'CDDDDDC#####CDDCDDC', '###############C###', '###############C###', '###############C###', '###############C###', '###############C###', 'CDDDDDC#####CDDCDDC', 'D#####D#####D##C##D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#C#C#D#####D#C#C#D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC', '###################', '###################', '###################', '###################', '###################', 'CDDDDDC#####CDDDDDC', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#C#C#D#####D#C#C#D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('CCCCCCC#CCC#CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDC#CDC#####CDC#CDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC', '###################', '###################', '###################', '###################', '###################', 'CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDC#CDC#####CDC#CDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#CCC#CCCCCCC')
        .aisle('#######CCCCC#######', '#######DDDDD#######', '#######DDDDD#######', '##C#C##DDDDD##C#C##', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '##C#C##DDDDD##C#C##', '#######DDDDD#######', '#######DDDDD#######', '#######CCCCC#######')
        .aisle('######CCCCCCC######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '######CCCCCCC######')
        .aisle('######CCCCCCC######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '######CCCCCCC######')
        .aisle('######CCCCCCC######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '#######DAAAD#######', '##C#C##DAAAD##C#C##', '#######DAAAD#######', '#######DAAAD#######', '######CCCCCCC######')
        .aisle('#######CCCCC#######', '#######DDDDD#######', '#######DDDDD#######', '##C#C##DDDDD##C#C##', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '#######DDDDD#######', '##C#C##DDDDD##C#C##', '#######DDDDD#######', '#######DDDDD#######', '#######CCCCC#######')
        .aisle('CCCCCCC#CKC#CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDC#CDC#####CDC#CDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC', '###################', '###################', '###################', '###################', '###################', 'CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDC#CDC#####CDC#CDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#CCC#CCCCCCC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#C#C#D#####D#C#C#D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC', '###################', '###################', '###################', '###################', '###################', 'CDDDDDC#####CDDDDDC', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#C#C#D#####D#C#C#D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D##C##D#####D#####D', 'CDDCDDC#####CDDDDDC', '###C###############', '###C###############', '###C###############', '###C###############', '###C###############', 'CDDCDDC#####CDDDDDC', 'D##C##D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CAC#D#####D#CAC#D', 'D#AFA#########AFA#D', 'D#CAC#D#####D#CAC#D', 'D#####D#####D#C#C#D', 'CDD#DDC#####CDC#CDC', '##############C#C##', '##############C#C##', '##############C#C##', '##############C#C##', '##############C#C##', 'CDD#DDC#####CDC#CDC', 'D#####D#####D#C#C#D', 'D#CAC#D#####D#CAC#D', 'D#AFA#########AFA#D', 'D#CAC#D#####D#CAC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D##C##D#####D#####D', 'CDDCDDC#####CDDDDDC', '###C###############', '###C###############', '###C###############', '###C###############', '###C###############', 'CDDCDDC#####CDDDDDC', 'D##C##D#####D#####D', 'D#CCC#D#####D#CCC#D', 'D#CACCCCCCCCCCCAC#D', 'D#CCC#D#####D#CCC#D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('C#####C#####C#####C', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC', '###################', '###################', '###################', '###################', '###################', 'CDDDDDC#####CDDDDDC', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'D#####D#####D#####D', 'CDDDDDC#####CDDDDDC')
        .aisle('CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC', '###################', '###################', '###################', '###################', '###################', 'CCCCCCC#####CCCCCCC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CDDDDDC#####CDDDDDC', 'CCCCCCC#####CCCCCCC')
            .where('K', Predicates.controller(Predicates.blocks(definition.get())))
            .where("A", Predicates.blocks('antiblocksrechiseled:bright_white'))
            .where("E", Predicates.blocks('kubejs:conductive_glass'))
            .where("D", Predicates.blocks('gtceu:tempered_glass'))
            .where("F", Predicates.blocks('kubejs:awakened_draconium_coil_block'))
            .where("B", Predicates.blocks('kubejs:quantum_casing'))
            .where("C", Predicates.blocks('kubejs:superconductive_casing')
            .or(Predicates.autoAbilities(definition.getRecipeTypes()))
            .or(Predicates.abilities(PartAbility.MAINTENANCE))
        )
            .where('#', Predicates.any())
            .build()
        )
        .workableCasingRenderer("kubejs:block/casings/superconductive_casing", 'gtceu:block/multiblock/generator/large_plasma_turbine', true)
})