ServerEvents.recipes(sog => {

    sog.recipes.gtceu.assembler('conductive_casing')
    .itemInputs('8x gtceu:californite_plate', '2x kubejs:highly_superconducting_coil_block', '2x gtceu:uv_field_generator', '8x gtceu:neutron_reflector', '4x #gtceu:circuits/uhv', '8x gtceu:plascrete', '4x gtceu:draconium_plate')
    .inputFluids('gtceu:polybenzimidazole 1000')
    .itemOutputs('2x kubejs:superconductive_casing')
    .cleanroom(CleanroomType.STERILE_CLEANROOM)
    .duration(100)
    .EUt(GTValues.VA[GTValues.UIV]);
    
    sog.recipes.gtceu.assembler('conductive_glass')
    .itemInputs('8x gtceu:californite_plate', '2x kubejs:highly_superconducting_coil_block', '2x gtceu:uv_field_generator', '8x gtceu:neutron_reflector', '4x #gtceu:circuits/uhv', '4x gtceu:cleanroom_glass', '4x gtceu:draconium_plate')
    .inputFluids('gtceu:polybenzimidazole 1000')
    .itemOutputs('2x kubejs:conductive_glass')
    .cleanroom(CleanroomType.STERILE_CLEANROOM)
    .duration(100)
    .EUt(GTValues.VA[GTValues.UIV]);    

sog.recipes.gtceu.dimensionalmatter('saturn_primary_rp')
.notConsumable('kubejs:gravitational_fluctuation_module')
.itemInputs('kubejs:quantum_energy_capsule')
.circuit(20)
.dimension('ad_extendra:saturn')
.outputFluids('gtceu:crude_astral_flux_plasma 16000')
.duration(20*60)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.large_synchrotron_switcher('hyperionized_helium')
.notConsumable('kubejs:gravitational_fluctuation_module')
.dimension('ad_extendra:saturn_orbit')
.inputFluids('gtceu:helium_plasma 1000')
.outputFluids('gtceu:hyper_ionized_helium_plasma 16')
.duration(5)
.EUt(GTValues.VA[GTValues.UIV]);
sog.recipes.gtceu.blackhole_holder('astral_flux')
.dimension('ad_extendra:saturn_orbit')
.inputFluids('gtceu:crude_astral_flux_plasma 250')
.outputFluids('gtceu:astral_flux_plasma 250')
.duration(20*20)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.alloy_blast_smelter("infused_cosmic_matter")
.itemInputs('8x gtceu:heavy_duty_alloy_t4_dust', '2x draconicevolution:awakened_draconium_dust', '4x kubejs:reactive_chaos_dust')
.circuit(21)
.inputFluids('gtceu:raw_cosmic_matter 64000', 'gtceu:hyper_ionized_helium_plasma 250', 'gtceu:astral_flux_plasma 500')
.outputFluids(Fluid.of("gtceu:infused_cosmic_matter", 288))
.duration(20*305)
.dimension('ad_extendra:saturn_orbit')
.EUt(GTValues.VA[GTValues.UXV])
.blastFurnaceTemp(15000)
sog.recipes.gtceu.stasis_field("stabilized_raw_cosmic_matter")
.inputFluids('gtceu:infused_cosmic_matter 576')
.outputFluids(Fluid.of("gtceu:stabilized_raw_cosmic_matter", 288))
.duration(20*60)
.dimension('ad_extendra:saturn_orbit')
.EUt(GTValues.VA[GTValues.UXV])
sog.recipes.gtceu.plasma_nexus('cryogenic_neutron_flow')
.inputFluids('gtceu:liquid_oxygen 288', 'gtceu:neutronium 5000')
.outputFluids('gtceu:cryogenic_neutron_flow 144')
.EUt((GTValues.VA[GTValues.UIV]))
.duration(55)
sog.recipes.gtceu.quantum_cooling_chamber("cryo_compressed_cosmic_matter")
.inputFluids('gtceu:stabilized_raw_cosmic_matter 576', 'gtceu:cryogenic_neutron_flow 1996')
.outputFluids(Fluid.of("gtceu:cryo_compressed_raw_cosmic_matter", 288))
.duration(20*60)
.dimension('ad_extendra:saturn_orbit')
.EUt(GTValues.VA[GTValues.UXV])
sog.recipes.gtceu.stasis_phase_shifter("shifted_cosmic_matter_base")
.inputFluids('gtceu:cryo_compressed_raw_cosmic_matter 576', 'gtceu:antimatter 120')
.outputFluids(Fluid.of("gtceu:shifted_cosmic_matter_base", 288))
.duration(20*60)
.dimension('ad_extendra:saturn_orbit')
.EUt(GTValues.VA[GTValues.UXV])
sog.recipes.gtceu.blackhole_holder('eternal_singularity')
.dimension('ad_extendra:saturn_orbit')
.chancedInput("kubejs:singularity_data", 500, 0)
.itemOutputsRanged('avaritia:eternal_singularity', 1, 2)
.inputFluids('gtceu:antimatter 10')
.outputFluids('gtceu:eternity 1')
.duration(25)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.blackhole_holder('eternal_antimatter')
.dimension('ad_extendra:saturn_orbit')
.chancedInput("kubejs:elementary_data", 500, 0)
.inputFluids('gtceu:eternity 10')
.outputFluids('gtceu:antimatter 1000')
.duration(25)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.plasma_nexus('plasma_tempered_cosmic_matter_base')
.notConsumable('kubejs:plasma_data')
.inputFluids('gtceu:hypercharged_nebular_plasma 1000', 'gtceu:shifted_cosmic_matter_base 576')
.itemInputs('96x kubejs:reactive_chaos_dust')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:plasma_tempered_cosmic_matter_base_plasma 244')
.duration(20*20)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.large_synchrotron_switcher("hyper_dense_cosmic_matter_base")
.inputFluids('gtceu:plasma_tempered_cosmic_matter_base_plasma 576', 'gtceu:supercritical_californium_plasma 1000')
.outputFluids(Fluid.of("gtceu:hyper_dense_cosmic_matter_base_plasma", 288))
.duration(20*60)
.dimension('ad_extendra:saturn_orbit')
.EUt(GTValues.VA[GTValues.UIV])
sog.recipes.gtceu.plasma_nexus('refined_cosmic_matter_plasma')
.notConsumable('kubejs:plasma_data')
.inputFluids('gtceu:hypercharged_nebular_plasma 200', 'gtceu:hyper_dense_cosmic_matter_base_plasma 576')
.itemInputs('2x avaritia:eternal_singularity')
.outputFluids('gtceu:refined_cosmic_matter_plasma 576')
.duration(20*20)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.vacuum_freezer('cosmic_matter')
.inputFluids('gtceu:refined_cosmic_matter_plasma 100')
.outputFluids('gtceu:cosmic_matter 100')
.duration(2)
.EUt(GTValues.VA[GTValues.ZPM]);
sog.recipes.gtceu.large_synchrotron_switcher("pure_cosmic_matter")
.inputFluids('gtceu:cosmic_matter 288')
.itemOutputs('gtceu:pure_cosmic_matter_ingot')
.duration(25)
.EUt(GTValues.VA[GTValues.UIV])







sog.recipes.gtceu.plasma_nexus('hypercharged_nihonium')
.inputFluids('gtceu:nihonium 1800')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:hypercharged_nihonium_plasma 250')
.duration(35)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.plasma_nexus('hypercharged_oganesson')
.inputFluids('gtceu:oganesson 1800')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:hypercharged_oganesson_plasma 250')
.duration(35)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.plasma_nexus('hypercharged_nebular_plasma')
.inputFluids('gtceu:astral_flux_plasma 1800')
.itemInputs('96x kubejs:reactive_chaos_dust')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:hypercharged_nebular_plasma 250')
.duration(35)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.plasma_nexus('high_entropy_neptunium_plasma')
.inputFluids('gtceu:neptunium 1800')
.itemInputs('2x avaritia:eternal_singularity')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:high_entropy_neptunium_plasma 250')
.duration(35)
.EUt(GTValues.VA[GTValues.UXV]);
sog.recipes.gtceu.plasma_nexus('supercritical_californium')
.inputFluids('gtceu:californium 1800')
.itemInputs('avaritia:eternal_singularity')
.inputFluids('gtceu:cryogenic_neutron_flow 1000')
.outputFluids('gtceu:supercritical_californium_plasma 250')
.duration(35)
.EUt(GTValues.VA[GTValues.UXV]);


})