ServerEvents.recipes(sog => {

sog.recipes.gtceu.electric_blast_furnace('inifnity')
.itemInputs('64x gtceu:infinity_catalyst_dust')
.itemInputs('64x gtceu:infinity_catalyst_dust')
.itemInputs('64x gtceu:infinity_catalyst_dust')
.inputFluids('gtceu:universium 16000')
.inputFluids('gtceu:stellar_matter_plasma 32000')
.inputFluids('gtceu:eternity 16000')
.inputFluids('gtceu:molten_space_time 8000')
.itemOutputs('avaritia:infinity_ingot')
.blastFurnaceTemp(15450)
.duration(1400)
.EUt(GTValues.VA[GTValues.OpV]);

sog.recipes.gtceu.reinforced_atomicforge('molten_space_time')
.itemInputs('4x gtceu:space_time_ingot')
.outputFluids('gtceu:molten_space_time 144')
.duration(20*20)
.EUt(GTValues.VA[GTValues.OpV]);

sog.recipes.gtceu.reinforced_atomicforge('extreme_anvil')
.itemInputs('64x kubejs:space_time_heavy_plating')
.itemInputs('64x kubejs:space_time_heavy_plating')
.itemInputs('64x kubejs:space_time_heavy_plating')
.itemInputs('64x kubejs:space_time_heavy_plating')
.itemOutputs('avaritia:extreme_anvil')
.duration(144000)
.EUt(GTValues.VA[GTValues.OpV]);

sog.recipes.gtceu.reinforced_atomicforge('ennhanced_core')
.itemInputs('16x kubejs:infinity_heavy_plating')
.itemInputs('16x kubejs:eternity_nanites')
.itemInputs('16x kubejs:universium_nanites')
.itemInputs('16x kubejs:stellar_matter_nanites')
.itemInputs('16x kubejs:cosmic_matter_nanites')
.itemInputs('16x kubejs:infinity_heavy_plating')
.itemOutputs('avaritia:enhancement_core')
.duration(72000)
.EUt(GTValues.VA[GTValues.OpV]);

sog.recipes.gtceu.reinforced_atomicforge('eternity_nanites')
.itemInputs('256x gtceu:eternity_ingot')
.itemInputs('64x kubejs:energized_quantum_anomaly')
.itemOutputs('kubejs:eternity_nanites')
.duration(20)
.EUt(GTValues.VA[GTValues.OpV]);
sog.recipes.gtceu.reinforced_atomicforge('cosmic_matter_nanites')
.itemInputs('256x gtceu:pure_cosmic_matter_ingot')
.itemInputs('64x kubejs:energized_quantum_anomaly')
.itemOutputs('kubejs:cosmic_matter_nanites')
.duration(20)
.EUt(GTValues.VA[GTValues.OpV]);
sog.recipes.gtceu.reinforced_atomicforge('stellar_matter_nanites')
.itemInputs('256x gtceu:stellar_matter_plasma_ingot')
.itemInputs('64x kubejs:energized_quantum_anomaly')
.itemOutputs('kubejs:stellar_matter_nanites')
.duration(20)
.EUt(GTValues.VA[GTValues.OpV]);
sog.recipes.gtceu.reinforced_atomicforge('universium_nanites')
.itemInputs('256x gtceu:universium_ingot')
.itemInputs('64x kubejs:energized_quantum_anomaly')
.itemOutputs('kubejs:universium_nanites')
.duration(20)
.EUt(GTValues.VA[GTValues.OpV]);
sog.recipes.gtceu.reinforced_atomicforge('infinity_catalyst')
.itemInputs('256x avaritia:infinity_ingot')
.itemInputs('64x kubejs:energized_quantum_anomaly')
.itemInputs('256x avaritia:eternal_singularity')
.itemOutputs('avaritia:infinity_catalyst')
.duration(36000)
.EUt(GTValues.VA[GTValues.OpV]);

sog.recipes.gtceu.large_chemical_reactor('dimensional_circuit_board')
.inputFluids('gtceu:universium 16000')
.itemInputs('2x kubejs:cosmic_circuit_board', 'kubejs:extremely_advanced_soc', '4x gtceu:dense_infinity_plate')
.itemOutputs('kubejs:dimensional_circuit_board')
.EUt((GTValues.VA[GTValues.OpV]))
.duration(20*45)
sog.recipes.gtceu.large_chemical_reactor('dimensional_printed_circuit_board')
.inputFluids('gtceu:universium 64000', 'gtceu:eternity 20000')
.itemInputs('kubejs:dimensional_circuit_board', '256x gtceu:fine_eternity_wire', '64x gtceu:infinity_bolt')
.itemOutputs('kubejs:dimensional_printed_circuit_board')
.EUt((GTValues.VA[GTValues.OpV]))
.duration(20*115)
})