
ServerEvents.recipes(event => {

event.recipes.gtceu.qsp('cosmic_neutronium')
    .notConsumable('kubejs:cosmic_projector_module')
    .itemInputs('gtceu:neutronium_ingot', '8x gtceu:resonant_essence_ingot')
    .inputFluids(Fluid.of('gtceu:neutronium', 1440))
    .inputFluids(Fluid.of('gtceu:condensed_star_matter', 10000))
    .itemOutputs('16x gtceu:cosmic_neutronium_dust')
    .duration(20)
    .EUt(GTValues.VA[GTValues.UEV]);
event.recipes.gtceu.qsp('hrsoc')
    .notConsumable('kubejs:cosmic_projector_module')
    .itemInputs('gtceu:highly_advanced_soc', '8x gtceu:resonant_essence_ingot')
    .inputFluids(Fluid.of('gtceu:neutronium', 1440))
    .inputFluids(Fluid.of('gtceu:antimatter', 512))
    .itemOutputs('kubejs:highly_resonative_soc')
    .duration(800)
    .EUt(GTValues.VA[GTValues.UEV]);

    event.recipes.gtceu.qsp('drilloverworld')
    .notConsumable('kubejs:drilling_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule')
    .itemOutputsRanged('gtceu:raw_nickel', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_graphite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_coal', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_diamond', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_lapis', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_redstone', 10000, 45000)
    .itemOutputsRanged('minecraft:raw_copper', 10000, 45000)
    .itemOutputsRanged('minecraft:raw_gold', 10000, 45000)
    .itemOutputsRanged('minecraft:raw_iron', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_tin', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_amethyst', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_green_sapphire', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_sphalerite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_apatite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_cobaltite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_certus_quartz', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_quartzite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_salt', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_saltpeter', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_beryllium', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_lead', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_silver', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_barite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_stibnite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_emerald', 10000, 45000)
    .circuit(1)
    .duration(6000)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('drillmoon')
    .notConsumable('kubejs:drilling_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule')
    .itemOutputsRanged('ad_astra:raw_desh', 10000, 45000)
    .itemOutputsRanged('gtceu:star_matter_nugget', 1000, 10000)
    .itemOutputsRanged('gtceu:rare_earth_dust', 10000, 45000)
    .itemOutputsRanged('gtceu:borax_dust', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_uraninite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_vanadium_magnetite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_molybdenite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_tantalite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_zeolite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_bastnasite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_chromite', 10000, 45000)
    .outputFluids('gtceu:titanium 14400000')
    .circuit(2)
    .duration(6000)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('pumpoverworld')
    .notConsumable('kubejs:pumping_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule', 'minecraft:dirt')
    .itemOutputsRanged('gtceu:raw_oilsands', 1000, 10000)
    .outputFluids('gtceu:oil 14400000')
    .outputFluids('gtceu:natural_gas 14400000')
    .outputFluids('gtceu:oxygen 14400000')
    .outputFluids('gtceu:hydrogen 14400000')
    .outputFluids('gtceu:nitrogen 14400000')
    .outputFluids('minecraft:lava 14400000')
    .outputFluids('gtceu:air 14400000')
    .circuit(1)
    .duration(6000)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('pumpnether')
    .notConsumable('kubejs:pumping_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule', 'minecraft:netherrack')
    .outputFluids('gtceu:nether_air 14400000')
    .circuit(1)
    .duration(600)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('pumpend')
    .notConsumable('kubejs:pumping_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule', 'minecraft:end_stone')
    .outputFluids('gtceu:ender_air 14400000', 'gtceu:helium 144000000')
    .circuit(1)
    .duration(600)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('polyethylene')
    .notConsumable('kubejs:pumping_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule', '32x gtceu:sulfur_dust')
    .inputFluids('minecraft:water 1000')
    .outputFluids('gtceu:polyethylene 1000000')
    .outputFluids('gtceu:polytetrafluoroethylene 1000000')
    .circuit(2)
    .duration(100)
    .EUt(GTValues.VA[GTValues.UEV]);
    event.recipes.gtceu.qsp('polybenzimidazole')
    .notConsumable('kubejs:pumping_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule', '256x gtceu:raw_coal')
    .inputFluids('minecraft:water 1000')
    .outputFluids('gtceu:polybenzimidazole 1000000')
    .circuit(2)
    .duration(100)
    .EUt(GTValues.VA[GTValues.UEV]);

    event.recipes.gtceu.qsp('drillmars')
    .notConsumable('kubejs:drilling_projector_module')
    .itemInputs('4x kubejs:quantum_energy_capsule')
    .itemOutputsRanged('ad_astra:raw_ostrum', 10000, 45000)
    .itemOutputsRanged('gtceu:star_matter_nugget', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_naquadah', 10000, 45000)
    .itemOutputsRanged('gtceu:antimony_trifluoride_dust', 10000, 45000)
    .itemOutputsRanged('minecraft:netherite_scrap', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_plutonium', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_galena', 10000, 45000)
    .itemOutputsRanged('minecraft:gunpowder', 10000, 45000)
    .itemOutputsRanged('minecraft:ender_pearl', 1, 45000)
    .itemOutputsRanged('gtceu:raw_platinum', 10000, 45000)
    .itemOutputsRanged('minecraft:glowstone_dust', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_uraninite', 10000, 45000)
    .itemOutputsRanged('gtceu:raw_sulfur', 10000, 45000)
    .circuit(3)
    .duration(6000)
    .EUt(GTValues.VA[GTValues.UEV]);

    event.recipes.gtceu.qsp('fusion_europium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:neodymium', 16))
    .inputFluids(Fluid.of('gtceu:hydrogen', 375))
    .outputFluids(Fluid.of('gtceu:europium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_chromium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:vanadium', 16))
    .inputFluids(Fluid.of('gtceu:hydrogen', 125))
    .outputFluids(Fluid.of('gtceu:chromium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_americium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:lutetium', 32))
    .inputFluids(Fluid.of('gtceu:chromium', 32))
    .outputFluids(Fluid.of('gtceu:americium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.ZPM]);
    event.recipes.gtceu.qsp('fusion_tritanium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:titanium', 32))
    .inputFluids(Fluid.of('gtceu:duranium', 32))
    .outputFluids(Fluid.of('gtceu:tritanium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_plut241_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:krypton', 125))
    .inputFluids(Fluid.of('gtceu:cerium', 16))
    .outputFluids(Fluid.of('gtceu:plutonium_241 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.ZPM]);
    event.recipes.gtceu.qsp('fusion_lutetium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:lanthanum', 16))
    .inputFluids(Fluid.of('gtceu:silicon', 16))
    .outputFluids(Fluid.of('gtceu:lutetium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.IV]);
    event.recipes.gtceu.qsp('fusion_neutronium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:americium', 128))
    .inputFluids(Fluid.of('gtceu:naquadria', 128))
    .outputFluids(Fluid.of('gtceu:neutronium 1000'))
    .duration(200)
    .EUt(GTValues.VA[GTValues.ZPM]);
    event.recipes.gtceu.qsp('fusion_plutonium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:xenon', 125))
    .inputFluids(Fluid.of('gtceu:zinc', 16))
    .outputFluids(Fluid.of('gtceu:plutonium 1000'))
    .duration(120)
    .EUt(GTValues.VA[GTValues.ZPM]);
    event.recipes.gtceu.qsp('fusion_naquadria_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:enriched_naquadah', 16))
    .inputFluids(Fluid.of('gtceu:radon', 125))
    .outputFluids(Fluid.of('gtceu:naquadria 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.ZPM]);
    event.recipes.gtceu.qsp('fusion_duranium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:gallium', 16))
    .inputFluids(Fluid.of('gtceu:radon', 125))
    .outputFluids(Fluid.of('gtceu:duranium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_uranium_235_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:magnesium', 16))
    .inputFluids(Fluid.of('gtceu:mercury', 125))
    .outputFluids(Fluid.of('gtceu:uranium_235 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_darmstadtium_235_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:resonant_naquadah', 16))
    .inputFluids(Fluid.of('gtceu:ruthenium', 16))
    .outputFluids(Fluid.of('gtceu:darmstadtium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_uranium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:gold', 16))
    .inputFluids(Fluid.of('gtceu:aluminium', 16))
    .outputFluids(Fluid.of('gtceu:uranium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_indium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:silver', 144))
    .inputFluids(Fluid.of('gtceu:lithium', 144))
    .outputFluids(Fluid.of('gtceu:indium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
    event.recipes.gtceu.qsp('fusion_osmium_qsp')
    .notConsumable('kubejs:fusion_projector_module')
    .inputFluids(Fluid.of('gtceu:silver', 16))
    .inputFluids(Fluid.of('gtceu:copper', 16))
    .outputFluids(Fluid.of('gtceu:osmium 1000'))
    .duration(60)
    .EUt(GTValues.VA[GTValues.LuV]);
})