
GTCEuStartupEvents.registry('gtceu:dimension_marker', event => {
        event.create('ad_extendra:saturn')
        .iconSupplier(() => Item.of('ad_extendra:saturn_globe').getItem())
        .tier(0)
        .overrideName('Saturn')
        event.create('ad_astra:venus')
        .iconSupplier(() => Item.of('ad_astra:venus_globe').getItem())
        .tier(0)
        .overrideName('Venus')
        event.create('ad_astra:mercury')
        .iconSupplier(() => Item.of('ad_astra:mercury_globe').getItem())
        .tier(0)
        .overrideName('Mercury')
        event.create('ad_astra:moon')
        .iconSupplier(() => Item.of('ad_astra:moon_globe').getItem())
        .tier(0)
        .overrideName('Moon')
        event.create('sogcore:asteroid_belt')
        .iconSupplier(() => Item.of('kubejs:asteroid_belt_marker').getItem())
        .tier(0)
        .overrideName('Asteroid Belt')
})